# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(846, 605)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.three_chord = QtWidgets.QPushButton(self.centralwidget)
        self.three_chord.setObjectName("three_chord")
        self.gridLayout.addWidget(self.three_chord, 1, 3, 1, 1)
        self.five_chord = QtWidgets.QPushButton(self.centralwidget)
        self.five_chord.setObjectName("five_chord")
        self.gridLayout.addWidget(self.five_chord, 1, 5, 1, 1)
        self.one_chord = QtWidgets.QPushButton(self.centralwidget)
        self.one_chord.setAutoExclusive(False)
        self.one_chord.setAutoRepeatDelay(295)
        self.one_chord.setObjectName("one_chord")
        self.gridLayout.addWidget(self.one_chord, 1, 0, 1, 1)
        self.four_chrod = QtWidgets.QPushButton(self.centralwidget)
        self.four_chrod.setObjectName("four_chrod")
        self.gridLayout.addWidget(self.four_chrod, 1, 4, 1, 1)
        self.seven_chord = QtWidgets.QPushButton(self.centralwidget)
        self.seven_chord.setObjectName("seven_chord")
        self.gridLayout.addWidget(self.seven_chord, 1, 7, 1, 1)
        self.six_chord = QtWidgets.QPushButton(self.centralwidget)
        self.six_chord.setObjectName("six_chord")
        self.gridLayout.addWidget(self.six_chord, 1, 6, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 2, 4, 1, 1)
        self.viewChords = QtWidgets.QPushButton(self.centralwidget)
        self.viewChords.setObjectName("viewChords")
        self.gridLayout.addWidget(self.viewChords, 2, 5, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        self.two_chord = QtWidgets.QPushButton(self.centralwidget)
        self.two_chord.setObjectName("two_chord")
        self.gridLayout.addWidget(self.two_chord, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 846, 22))
        self.menubar.setObjectName("menubar")
        self.menuMusic_App = QtWidgets.QMenu(self.menubar)
        self.menuMusic_App.setObjectName("menuMusic_App")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMusic_App.addAction(self.actionOpen)
        self.menuMusic_App.addAction(self.actionSave)
        self.menuMusic_App.addAction(self.actionExit)
        self.menuMusic_App.addSeparator()
        self.menubar.addAction(self.menuMusic_App.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Melody Maker"))
        self.three_chord.setText(_translate("MainWindow", "III"))
        self.three_chord.setShortcut(_translate("MainWindow", "D"))
        self.five_chord.setText(_translate("MainWindow", "V"))
        self.five_chord.setShortcut(_translate("MainWindow", "G"))
        self.one_chord.setText(_translate("MainWindow", "I"))
        self.one_chord.setShortcut(_translate("MainWindow", "A"))
        self.four_chrod.setText(_translate("MainWindow", "IV"))
        self.four_chrod.setShortcut(_translate("MainWindow", "F"))
        self.seven_chord.setText(_translate("MainWindow", "VII"))
        self.seven_chord.setShortcut(_translate("MainWindow", "J"))
        self.six_chord.setText(_translate("MainWindow", "VI"))
        self.six_chord.setShortcut(_translate("MainWindow", "H"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Gb"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Db"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Ab"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Eb"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Bb"))
        self.comboBox.setItemText(5, _translate("MainWindow", "F"))
        self.comboBox.setItemText(6, _translate("MainWindow", "C"))
        self.comboBox.setItemText(7, _translate("MainWindow", "G"))
        self.comboBox.setItemText(8, _translate("MainWindow", "D"))
        self.comboBox.setItemText(9, _translate("MainWindow", "A"))
        self.comboBox.setItemText(10, _translate("MainWindow", "E"))
        self.comboBox.setItemText(11, _translate("MainWindow", "B"))
        self.comboBox.setItemText(12, _translate("MainWindow", "F#"))
        self.viewChords.setText(_translate("MainWindow", "View Chords"))
        self.pushButton.setText(_translate("MainWindow", "7th Chords"))
        self.two_chord.setText(_translate("MainWindow", "II"))
        self.two_chord.setShortcut(_translate("MainWindow", "S"))
        self.menuMusic_App.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
