# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(846, 605)
        font = QtGui.QFont()
        font.setPointSize(14)
        mainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.two_chord = QtWidgets.QPushButton(self.centralwidget)
        self.two_chord.setObjectName("two_chord")
        self.gridLayout.addWidget(self.two_chord, 0, 2, 1, 1)
        self.three_chord = QtWidgets.QPushButton(self.centralwidget)
        self.three_chord.setObjectName("three_chord")
        self.gridLayout.addWidget(self.three_chord, 0, 3, 1, 1)
        self.four_chrod = QtWidgets.QPushButton(self.centralwidget)
        self.four_chrod.setObjectName("four_chrod")
        self.gridLayout.addWidget(self.four_chrod, 0, 4, 1, 1)
        self.five_chord = QtWidgets.QPushButton(self.centralwidget)
        self.five_chord.setObjectName("five_chord")
        self.gridLayout.addWidget(self.five_chord, 0, 5, 1, 1)
        self.six_chord = QtWidgets.QPushButton(self.centralwidget)
        self.six_chord.setObjectName("six_chord")
        self.gridLayout.addWidget(self.six_chord, 0, 6, 1, 1)
        self.seven_chord = QtWidgets.QPushButton(self.centralwidget)
        self.seven_chord.setObjectName("seven_chord")
        self.gridLayout.addWidget(self.seven_chord, 0, 7, 1, 1)
        self.one_chord = QtWidgets.QPushButton(self.centralwidget)
        self.one_chord.setObjectName("one_chord")
        self.gridLayout.addWidget(self.one_chord, 0, 0, 1, 1)
        self.select_key = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.select_key.setFont(font)
        self.select_key.setObjectName("select_key")
        self.select_key.addItem("")
        self.select_key.addItem("")
        self.select_key.addItem("")
        self.select_key.addItem("")
        self.select_key.addItem("")
        self.select_key.addItem("")
        self.select_key.addItem("")
        self.select_key.addItem("")
        self.select_key.addItem("")
        self.select_key.addItem("")
        self.select_key.addItem("")
        self.select_key.addItem("")
        self.select_key.addItem("")
        self.gridLayout.addWidget(self.select_key, 1, 4, 1, 1)
        self.viewChords = QtWidgets.QPushButton(self.centralwidget)
        self.viewChords.setObjectName("viewChords")
        self.gridLayout.addWidget(self.viewChords, 1, 5, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 846, 22))
        self.menubar.setObjectName("menubar")
        self.menuMusic_App = QtWidgets.QMenu(self.menubar)
        self.menuMusic_App.setObjectName("menuMusic_App")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(mainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(mainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(mainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMusic_App.addAction(self.actionOpen)
        self.menuMusic_App.addAction(self.actionSave)
        self.menuMusic_App.addAction(self.actionExit)
        self.menuMusic_App.addSeparator()
        self.menubar.addAction(self.menuMusic_App.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Melody Maker"))
        self.two_chord.setText(_translate("mainWindow", "II"))
        self.three_chord.setText(_translate("mainWindow", "III"))
        self.four_chrod.setText(_translate("mainWindow", "IV"))
        self.five_chord.setText(_translate("mainWindow", "V"))
        self.six_chord.setText(_translate("mainWindow", "VI"))
        self.seven_chord.setText(_translate("mainWindow", "VII"))
        self.one_chord.setText(_translate("mainWindow", "I"))
        self.select_key.setItemText(0, _translate("mainWindow", "Gb"))
        self.select_key.setItemText(1, _translate("mainWindow", "Db"))
        self.select_key.setItemText(2, _translate("mainWindow", "Ab"))
        self.select_key.setItemText(3, _translate("mainWindow", "Eb"))
        self.select_key.setItemText(4, _translate("mainWindow", "Bb"))
        self.select_key.setItemText(5, _translate("mainWindow", "F"))
        self.select_key.setItemText(6, _translate("mainWindow", "C"))
        self.select_key.setItemText(7, _translate("mainWindow", "G"))
        self.select_key.setItemText(8, _translate("mainWindow", "D"))
        self.select_key.setItemText(9, _translate("mainWindow", "A"))
        self.select_key.setItemText(10, _translate("mainWindow", "E"))
        self.select_key.setItemText(11, _translate("mainWindow", "B"))
        self.select_key.setItemText(12, _translate("mainWindow", "F#"))
        self.viewChords.setText(_translate("mainWindow", "View Chords"))
        self.pushButton.setText(_translate("mainWindow", "7th Chords"))
        self.menuMusic_App.setTitle(_translate("mainWindow", "File"))
        self.actionOpen.setText(_translate("mainWindow", "Open"))
        self.actionSave.setText(_translate("mainWindow", "Save"))
        self.actionExit.setText(_translate("mainWindow", "Exit"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
